import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Learn WIth Us</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logotop.png" />
      </Head>
    
    <h1>hello from joseph kitheka</h1>
      
    </div>
  )
}
