import React from 'react';
import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header';

export default function Home() {
  return (
    <>
    <div>
      <Head>
        <title>Learn WIth Us</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logotop.png" />
      </Head>
    
      {/* header-components */}
      <Header />
    
    </div>
    </>
  )
}
